spring.application.name=Arriendo
server.port=8080

spring.data.mongodb.uri=mongodb+srv://maxihuerta_db_user:6nOo7ULu9UD7Uine@camionessa.00fvf3k.mongodb.net/arriendo
spring.data.mongodb.auto-index-creation=true

# URLs de servicios remotos (Feign)
cliente.service.url=http://localhost:8081
camion.service.url=http://localhost:8082
usuario.service.url=http://localhost:8083

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG