spring.application.name=camion
server.port=8082

spring.data.mongodb.uri=mongodb+srv://maxihuerta_db_user:6nOo7ULu9UD7Uine@camionessa.00fvf3k.mongodb.net/camion
spring.data.mongodb.auto-index-creation=true

# Configuración de Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG